---
- name: MONGODB 3.4 | Configurar o proxy no yum.conf
  lineinfile: "dest=/etc/yum.conf
           state=present
           line='proxy={{ proxyinfo }}'"

- name: MONGODB 3.4 | Desabilitar SELINUX
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

- name: MONGODB 3.4 | Parar Firewalld
  service: name=firewalld state=stopped

- name: MONGODB 3.4 | Desabilitar Firewalld
  service: name=firewalld enabled=no

- name: MONGODB 3.4 | Configurar arquivo /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item.line }}"
  with_items:
    - { line: '{{ mongodb01_ip_server }}     {{ mongodb01_server_name }}     {{ mongodb01_server_name }}.netshoes.local' }
    - { line: '{{ mongodb02_ip_server }}     {{ mongodb02_server_name }}     {{ mongodb01_server_name }}.netshoes.local' }
    - { line: '{{ mongodb03_ip_server }}     {{ mongodb03_server_name }}     {{ mongodb01_server_name }}.netshoes.local' }

- name: MONGODB 3.4 | Copiar arquivo de repositorio do mongodb 3.4 (mongodb-org.repo)
  copy: src=files/mongodb-org.repo dest=/etc/yum.repos.d/mongodb-org.repo

- name: MONGODB 3.4 | Configurar hugepage
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name: MONGODB 3.4 | Configurar hugepage
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"

- name: MONGODB 3.4 | Configurar blockdev no LV onde estará o mongodb
  shell: "blockdev --setra 256 {{ lvpath_mongodb }}"

- name: MONGODB 3.4 | Instalar pymongo do Python
  yum: name=python-setuptools state=latest

- name: MONGODB 3.4 | Instalar bibliotecas do python
  easy_install: name=pymongo state=latest
  environment:
    http_proxy: {{ proxyinfo }}
    https_proxy: {{ proxyinfo }}
